// This is a required an autogenerated file from the Zesty.io NextJS integration
// This file is overwritten everytime the integration script is run
import ClippingZestyModel from './ClippingZestyModel';
import WidgetZestyModel from './WidgetZestyModel';
import MarketingAnnoucementZestyModel from './MarketingAnnoucementZestyModel';
import ReviewZestyModel from './ReviewZestyModel';
import MainNavigationZestyModel from './MainNavigationZestyModel';
import PersonaContentZestyModel from './PersonaContentZestyModel';
import CustomerBrandZestyModel from './CustomerBrandZestyModel';
import CustomerHighlightZestyModel from './CustomerHighlightZestyModel';
import LandingPageVariationZestyModel from './LandingPageVariationZestyModel';
import TeamMemberZestyModel from './TeamMemberZestyModel';
import FeatureZestyModel from './FeatureZestyModel';
import IntegrationPartnerZestyModel from './IntegrationPartnerZestyModel';
import IntegrationTypeZestyModel from './IntegrationTypeZestyModel';
import PricingTierZestyModel from './PricingTierZestyModel';
import PartnerZestyModel from './PartnerZestyModel';
import HeroZestyModel from './HeroZestyModel';
import PlatformSectionZestyModel from './PlatformSectionZestyModel';
import CategoryZestyModel from './CategoryZestyModel';
import ArticleZestyModel from './ArticleZestyModel';
import TagZestyModel from './TagZestyModel';
import AuthorZestyModel from './AuthorZestyModel';
import UseCaseZestyModel from './UseCaseZestyModel';
import LandingPageZestyModel from './LandingPageZestyModel';
import ProductExplainerZestyModel from './ProductExplainerZestyModel';
import HomepageZestyModel from './HomepageZestyModel';
import SimplePageZestyModel from './SimplePageZestyModel';
import MindshareZestyModel from './MindshareZestyModel';
import MindshareAuthorZestyModel from './MindshareAuthorZestyModel';
import AboutZestyModel from './AboutZestyModel';
import SalesPeopleZestyModel from './SalesPeopleZestyModel';
import ProductZestyModel from './ProductZestyModel';
import IntegrationZestyModel from './IntegrationZestyModel';
import PricingZestyModel from './PricingZestyModel';
import OurpartnerZestyModel from './OurpartnerZestyModel';
import HeroHompageZestyModel from './HeroHompageZestyModel';
import WhyZestyZestyModel from './WhyZestyZestyModel';
import ProductOverviewZestyModel from './ProductOverviewZestyModel';
import TechnologyOverviewZestyModel from './TechnologyOverviewZestyModel';
import CaseStudyZestyModel from './CaseStudyZestyModel';
import AgencyPartnerZestyModel from './AgencyPartnerZestyModel';
import ClientZestyModel from './ClientZestyModel';
import Header from './Header';
import Footer from './Footer';

export {

    ClippingZestyModel,
    WidgetZestyModel,
    MarketingAnnoucementZestyModel,
    ReviewZestyModel,
    MainNavigationZestyModel,
    PersonaContentZestyModel,
    CustomerBrandZestyModel,
    CustomerHighlightZestyModel,
    LandingPageVariationZestyModel,
    TeamMemberZestyModel,
    FeatureZestyModel,
    IntegrationPartnerZestyModel,
    IntegrationTypeZestyModel,
    PricingTierZestyModel,
    PartnerZestyModel,
    HeroZestyModel,
    PlatformSectionZestyModel,
    CategoryZestyModel,
    ArticleZestyModel,
    TagZestyModel,
    AuthorZestyModel,
    UseCaseZestyModel,
    LandingPageZestyModel,
    ProductExplainerZestyModel,
    HomepageZestyModel,
    SimplePageZestyModel,
    MindshareZestyModel,
    MindshareAuthorZestyModel,
    AboutZestyModel,
    SalesPeopleZestyModel,
    ProductZestyModel,
    IntegrationZestyModel,
    PricingZestyModel,
    OurpartnerZestyModel,
    HeroHompageZestyModel,
    WhyZestyZestyModel,
    ProductOverviewZestyModel,
    TechnologyOverviewZestyModel,
    CaseStudyZestyModel,
    AgencyPartnerZestyModel,
    ClientZestyModel,
    Footer,
    Header
}