// This is a required an autogenerated file from the Zesty.io NextJS integration
// This file is overwritten everytime the integration script is run
import Clipping from './Clipping';
import Widget from './Widget';
import MarketingAnnoucement from './MarketingAnnoucement';
import Review from './Review';
import MainNavigation from './MainNavigation';
import PersonaContent from './PersonaContent';
import CustomerBrand from './CustomerBrand';
import CustomerHighlight from './CustomerHighlight';
import LandingPageVariation from './LandingPageVariation';
import TeamMember from './TeamMember';
import Feature from './Feature';
import IntegrationPartner from './IntegrationPartner';
import IntegrationType from './IntegrationType';
import PricingTier from './PricingTier';
import Partner from './Partner';
import Hero from './Hero';
import PlatformSection from './PlatformSection';
import NewNavigation from './NewNavigation';
import Category from './Category';
import Article from './Article';
import Tag from './Tag';
import Author from './Author';
import UseCase from './UseCase';
import LandingPage from './LandingPage';
import ProductExplainer from './ProductExplainer';
import Homepage from './Homepage';
import SimplePage from './SimplePage';
import Mindshare from './Mindshare';
import MindshareAuthor from './MindshareAuthor';
import About from './About';
import SalesPeople from './SalesPeople';
import Product from './Product';
import Integration from './Integration';
import Pricing from './Pricing';
import Ourpartner from './Ourpartner';
import HeroHompage from './HeroHompage';
import WhyZesty from './WhyZesty';
import ProductOverview from './ProductOverview';
import TechnologyOverview from './TechnologyOverview';
import CaseStudy from './CaseStudy';
import AgencyPartner from './AgencyPartner';
import Client from './Client';
import Contact from './Contact';
import New from './New';
import Career from './Career';
import DeveloperResource from './DeveloperResource';
import EventsAndWebinar from './EventsAndWebinar';

export {

    Clipping,
    Widget,
    MarketingAnnoucement,
    Review,
    MainNavigation,
    PersonaContent,
    CustomerBrand,
    CustomerHighlight,
    LandingPageVariation,
    TeamMember,
    Feature,
    IntegrationPartner,
    IntegrationType,
    PricingTier,
    Partner,
    Hero,
    PlatformSection,
    NewNavigation,
    Category,
    Article,
    Tag,
    Author,
    UseCase,
    LandingPage,
    ProductExplainer,
    Homepage,
    SimplePage,
    Mindshare,
    MindshareAuthor,
    About,
    SalesPeople,
    Product,
    Integration,
    Pricing,
    Ourpartner,
    HeroHompage,
    WhyZesty,
    ProductOverview,
    TechnologyOverview,
    CaseStudy,
    AgencyPartner,
    Client,
    Contact,
    New,
    Career,
    DeveloperResource,
    EventsAndWebinar,
}