// This is a required an autogenerated file from the Zesty.io NextJS integration
// This file is overwritten everytime the integration script is run
import Clipping from './Clipping';
import Widget from './Widget';
import MarketingAnnoucement from './MarketingAnnoucement';
import Review from './Review';
import MainNavigation from './MainNavigation';
import PersonaContent from './PersonaContent';
import CustomerBrand from './CustomerBrand';
import CustomerHighlight from './CustomerHighlight';
import LandingPageVariation from './LandingPageVariation';
import TeamMember from './TeamMember';
import Feature from './Feature';
import PricingTier from './PricingTier';
import Partner from './Partner';
import Hero from './Hero';
import PlatformSection from './PlatformSection';
import NewNavigation from './NewNavigation';
import DeveloperResourceCard from './DeveloperResourceCard';
import ClientCard from './ClientCard';
import AgencyPartnerCard from './AgencyPartnerCard';
import AboutStat from './AboutStat';
import JobListing from './JobListing';
import EventHost from './EventHost';
import NewsArticleAuthor from './NewsArticleAuthor';
import DemoPageItem from './DemoPageItem';
import Cta from './Cta';
import Benefit from './Benefit';
import ProofPoint from './ProofPoint';
import PlatformOverviewCard from './PlatformOverviewCard';
import FeaturesTile from './FeaturesTile';
import TechnologyBenefit from './TechnologyBenefit';
import Faq from './Faq';
import PricingLever from './PricingLever';
import PpcZestyKeyAttribute from './PpcZestyKeyAttribute';
import BrandAsset from './BrandAsset';
import IntegrationsBenefit from './IntegrationsBenefit';
import Category from './Category';
import Article from './Article';
import Tag from './Tag';
import Author from './Author';
import LandingPage from './LandingPage';
import ProductExplainer from './ProductExplainer';
import Event from './Event';
import LongFormPpc from './LongFormPpc';
import PpcShortForm from './PpcShortForm';
import IntegrationsIndividualPage from './IntegrationsIndividualPage';
import GatedContentPage from './GatedContentPage';
import Homepage from './Homepage';
import SimplePage from './SimplePage';
import Mindshare from './Mindshare';
import MindshareAuthor from './MindshareAuthor';
import About from './About';
import SalesPeople from './SalesPeople';
import Pricing from './Pricing';
import Ourpartner from './Ourpartner';
import HeroHompage from './HeroHompage';
import WhyZesty from './WhyZesty';
import PlatformOverview from './PlatformOverview';
import TechnologyOverview from './TechnologyOverview';
import CaseStudy from './CaseStudy';
import AgencyPartner from './AgencyPartner';
import Client from './Client';
import Contact from './Contact';
import Career from './Career';
import DeveloperResource from './DeveloperResource';
import EventsAndWebinar from './EventsAndWebinar';
import Demo from './Demo';
import Ppc from './Ppc';
import Brand from './Brand';
import Integration from './Integration';
import CapterraLandingPage from './CapterraLandingPage';
import Header from './Header';
import Footer from './Footer';

export {

    Clipping,
    Widget,
    MarketingAnnoucement,
    Review,
    MainNavigation,
    PersonaContent,
    CustomerBrand,
    CustomerHighlight,
    LandingPageVariation,
    TeamMember,
    Feature,
    PricingTier,
    Partner,
    Hero,
    PlatformSection,
    NewNavigation,
    DeveloperResourceCard,
    ClientCard,
    AgencyPartnerCard,
    AboutStat,
    JobListing,
    EventHost,
    NewsArticleAuthor,
    DemoPageItem,
    Cta,
    Benefit,
    ProofPoint,
    PlatformOverviewCard,
    FeaturesTile,
    TechnologyBenefit,
    Faq,
    PricingLever,
    PpcZestyKeyAttribute,
    BrandAsset,
    IntegrationsBenefit,
    Category,
    Article,
    Tag,
    Author,
    LandingPage,
    ProductExplainer,
    Event,
    LongFormPpc,
    PpcShortForm,
    IntegrationsIndividualPage,
    GatedContentPage,
    Homepage,
    SimplePage,
    Mindshare,
    MindshareAuthor,
    About,
    SalesPeople,
    Pricing,
    Ourpartner,
    HeroHompage,
    WhyZesty,
    PlatformOverview,
    TechnologyOverview,
    CaseStudy,
    AgencyPartner,
    Client,
    Contact,
    Career,
    DeveloperResource,
    EventsAndWebinar,
    Demo,
    Ppc,
    Brand,
    Integration,
    CapterraLandingPage,
    Footer,
    Header
}