export const baseroles = [
  {
    ZUID: '31-71cfc74-0wn3r',
    desc: 'Full access to all sections: Content, Media, Web IDE, Leads, Analytics, Schema, Health, Audit Trail, and Settings. ',
    name: 'Owner',
    accessLevel: 0,
    label: 'Owner',
    value: 'owner',
  },
  {
    ZUID: '31-71cfc74-4dm13',
    desc: 'Admins have the same privileges as the Owner role except for deleting other users.',
    name: 'Admin',
    accessLevel: 1,
    label: 'Admin',
    value: 'admin',
  },
  {
    ZUID: '31-71cfc74-d3v3l0p3r',
    desc: 'Access to: Content, Media, Web IDE, Leads, Analytics, Schema, Health, and Settings sections.',
    name: 'Developer',
    accessLevel: 2,
    label: 'Developer',
    value: 'developer',
  },
  {
    ZUID: '31-71cfc74-s30',
    desc: 'Access to: Content, Media, Leads, Analytics, and Health sections.',
    name: 'SEO',
    accessLevel: 3,
    label: 'SEO',
    value: 'seo',
  },
  {
    ZUID: '31-71cfc74-p0bl1shr',
    name: 'Publisher',
    desc: 'Access to Content, Media, Leads, and Analytics sections. ',
    accessLevel: 4,
    label: 'Publisher',
    value: 'publisher',
  },
  {
    ZUID: '31-71cfc74-c0ntr1b0t0r',
    desc: 'Access to Content and Media sections. ',
    name: 'Contributor',
    accessLevel: 5,
    label: 'Contributor',
    value: 'contributor',
  },
];
